import { useEffect, useState } from 'react';
import { ArrowDown, ArrowRight, ArrowUpRight, Github, Mail, Menu, Phone, X, Code2, Database, BrainCircuit, MapPin, ExternalLink, Terminal, Layers3, GraduationCap, Award, BriefcaseBusiness } from 'lucide-react';

const projects = [
 {n:'01',name:'Adah Foundation',type:'Web application',desc:'A responsive digital platform built to give an organization’s outreach a clear, welcoming home.',stack:'Responsive UI · Web development',url:'https://adahfoundation.netlify.app/',action:'Visit live site',tone:'lime'},
 {n:'02',name:'Quantora Technologies',type:'Corporate platform',desc:'A polished corporate web presence, pairing clear information architecture with a modern responsive interface.',stack:'Frontend architecture · Responsive design',url:'https://dev.plankraftinternational.com/',action:'Visit live site',tone:'coral'},
 {n:'03',name:'Ober Boys High School',type:'Institutional web frontend',desc:'A structured school website with considered navigation, clear page layouts and optimized static assets.',stack:'Web frontend · Static assets',url:'https://idyllic-naiad-c42658.netlify.app/',action:'Visit live site',tone:'blue'},
 {n:'04',name:'Crime Hotspot Detection System',type:'Geospatial machine learning',desc:'An analytics application that uses clustering to identify and visualize patterns in crime incidents.',stack:'Python · K-Means · DBSCAN · Streamlit',url:'https://github.com/Josephat200/crime-incident-detection-.git',action:'Explore repository',tone:'coral'},
 {n:'05',name:'Iris Flower Classification Platform',type:'Applied machine learning',desc:'An interactive classifier that predicts Iris species using a supervised Scikit-learn model.',stack:'Python · Scikit-learn · Streamlit',url:'https://github.com/Josephat200/iris-flower-machine-learning.git',action:'Explore repository',tone:'lime'},
 {n:'06',name:'Enterprise Finance Management System',type:'Full-stack application',desc:'A finance tool for recording transactions, monitoring activity, managing data and producing reports.',stack:'Full-stack · Data management · Reporting',url:'https://finance-jtmt.onrender.com/',action:'Visit live site',tone:'blue'},
];
const skills = [
 {icon:Code2,title:'Web & software',items:['HTML5 / CSS3','JavaScript (ES6+)','React.js','Node.js / Express.js','PHP','Python','REST APIs','Responsive design']},
 {icon:BrainCircuit,title:'AI, ML & analysis',items:['NumPy / Pandas','Scikit-learn','TensorFlow','PyTorch','Exploratory analysis','Data cleaning','Visualization','Streamlit']},
 {icon:Database,title:'Data & tools',items:['MySQL / PostgreSQL','MongoDB / SQLite','Database design','SQL optimization','Git / GitHub','Jupyter Notebook','Docker (basic)','Netlify / Render']},
];
function App(){
 const [menu,setMenu]=useState(false);
 const closeMenu=()=>setMenu(false);

  useEffect(()=>{
   const revealItems=document.querySelectorAll<HTMLElement>('[data-reveal]');
   const prefersReducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;

   if(prefersReducedMotion || !('IntersectionObserver' in window)){
    revealItems.forEach(item=>{item.dataset.revealed='true'});
    return;
   }

   document.documentElement.classList.add('motion-ready');
   const observer=new IntersectionObserver(entries=>{
    entries.forEach(entry=>{
     if(!entry.isIntersecting)return;
     const item=entry.target as HTMLElement;
     item.dataset.revealed='true';
     observer.unobserve(item);
    });
   },{threshold:.14,rootMargin:'0px 0px -48px 0px'});

   revealItems.forEach(item=>observer.observe(item));
   return ()=>{
    observer.disconnect();
    document.documentElement.classList.remove('motion-ready');
   };
  },[]);

 return <div className="grain min-h-[100dvh] overflow-hidden bg-[#f3f0e8] text-[#1d2a40]">
  <header className="relative z-30 mx-auto flex max-w-[1440px] items-center justify-between px-6 py-5 md:px-12 xl:px-20">
   <a href="#home" onClick={closeMenu} aria-label="Josphat Omondi — home" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-[#1c2a40] text-sm font-bold text-[#f3f0e8]">JO</span><span className="font-semibold tracking-[-.03em]">Josphat Omondi<span className="ml-2 text-[#16836e]">/</span></span></a>
    <nav className="desktop-nav flex items-center gap-9 text-sm font-semibold text-[#5b6470]" aria-label="Main navigation"><a className="nav-link hover:text-[#16836e]" href="#work">Selected work</a><a className="nav-link hover:text-[#16836e]" href="#about">About</a><a className="nav-link hover:text-[#16836e]" href="#experience">Experience</a><a className="nav-link hover:text-[#16836e]" href="#contact">Contact</a></nav>
    <a href="mailto:omondijosephat2005@gmail.com" className="header-cta hidden rounded-full border border-[#1d2a40]/20 px-5 py-2.5 text-sm font-bold transition hover:bg-[#1d2a40] hover:text-[#f3f0e8] md:inline-flex">Let’s talk <ArrowUpRight size={16} className="ml-2"/></a>
    <button className="menu-open rounded-full border border-[#1d2a40]/20 p-2" aria-label={menu?'Close menu':'Open menu'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X size={20}/>:<Menu size={20}/>}</button>
  </header>
   {menu&&<nav className="mobile-navigation absolute inset-x-0 top-[76px] z-40 grid gap-1 border-b border-[#1d2a40]/15 bg-[#f3f0e8] px-6 py-5 shadow-lg md:hidden" aria-label="Mobile navigation"><a onClick={closeMenu} href="#work" className="py-3 font-semibold">Selected work</a><a onClick={closeMenu} href="#about" className="py-3 font-semibold">About</a><a onClick={closeMenu} href="#experience" className="py-3 font-semibold">Experience</a><a onClick={closeMenu} href="#contact" className="py-3 font-semibold">Contact</a></nav>}
  <main id="home">
   <section className="mx-auto grid max-w-[1440px] gap-10 px-6 pb-20 pt-10 md:grid-cols-[1.08fr_.92fr] md:items-center md:px-12 md:pb-28 md:pt-12 xl:px-20">
    <div className="relative z-10 reveal"><p className="mono mb-7 flex items-center gap-3 text-[11px] uppercase tracking-[.18em] text-[#16836e]"><span className="h-px w-9 bg-[#16836e]"/>Software engineer in the making · Kenya</p>
     <h1 className="display max-w-[850px] text-[clamp(3.8rem,8.6vw,8.8rem)] font-semibold leading-[.87] tracking-[-.085em]">Build with<br/><span className="text-[#16836e]">purpose.</span><br/>Learn in public.</h1>
     <p className="mt-8 max-w-[560px] text-lg leading-8 text-[#5b6470] md:text-xl">I’m Josphat Omondi — a Software Engineering student at Kirinyaga University turning thoughtful ideas into useful web products, practical machine learning and clear data stories.</p>
      <div className="mt-8 flex flex-wrap items-center gap-4"><a href="#work" className="primary-cta inline-flex items-center gap-3 rounded-full bg-[#1d2a40] px-6 py-4 text-sm font-bold text-[#f3f0e8] transition hover:bg-[#16836e]">Explore selected work <ArrowDown size={16}/></a><a href="mailto:omondijosephat2005@gmail.com" className="text-link inline-flex items-center gap-2 px-3 py-3 text-sm font-bold hover:text-[#16836e]">Get in touch <ArrowUpRight size={16}/></a></div>
     <div className="mt-12 flex flex-wrap gap-x-8 gap-y-3 text-xs font-semibold text-[#64707a]"><span className="flex items-center gap-2"><MapPin size={14} className="text-[#16836e]"/>Kirinyaga, Kenya</span><span className="flex items-center gap-2"><span aria-hidden="true" className="h-2 w-2 rounded-full bg-[#e97754]"/>Open to meaningful collaboration</span></div>
    </div>
     <div className="relative mx-auto w-full max-w-[510px] reveal md:ml-auto" style={{animationDelay:'.15s'}}><div className="portrait-note absolute -right-2 top-5 z-10 rotate-3 rounded-sm bg-[#d9f36f] px-4 py-3 shadow-md md:-right-6 md:top-12"><span className="mono text-[10px] uppercase tracking-widest">Curiosity, in practice</span><p className="display mt-1 text-xl font-semibold">Ideas → working things</p></div><div className="portrait-note absolute -left-3 bottom-7 z-10 -rotate-3 rounded-full border border-[#1d2a40]/20 bg-[#f3f0e8] px-5 py-3 text-sm font-semibold shadow-md md:-left-8"><span className="text-[#e97754]">●</span> Building across code + data</div><div className="portrait-frame relative h-[460px] overflow-hidden rounded-[48%_48%_12px_12px] bg-[#d4d8ce] md:h-[590px]"><img src="/images/josphat-omondi.jpeg" alt="Portrait of Josphat Omondi wearing a navy suit and tie" className="portrait-image h-full w-full object-cover object-[50%_30%]"/><div className="absolute inset-x-0 bottom-0 h-1/4 bg-gradient-to-t from-[#1d2a40]/20 to-transparent"/></div><span aria-hidden="true" className="absolute -bottom-7 right-6 -z-0 text-[100px] font-black leading-none text-[#16836e]/10 md:text-[160px]">JO</span></div>
   </section>
   <div className="overflow-hidden border-y border-[#1d2a40]/15 bg-[#1d2a40] py-4 text-[#f3f0e8]"><div className="marquee flex w-max items-center gap-7 whitespace-nowrap mono text-xs uppercase tracking-[.2em]">{Array.from({length:2}).map((_,i)=><span key={i} className="flex items-center gap-7">Full-stack development <i className="not-italic text-[#d9f36f]">/</i> Applied machine learning <i className="not-italic text-[#e97754]">/</i> Data analysis <i className="not-italic text-[#d9f36f]">/</i> Interfaces with intention <i className="not-italic text-[#e97754]">/</i></span>)}</div></div>
    <section id="work" className="mx-auto max-w-[1440px] px-6 py-24 md:px-12 md:py-32 xl:px-20"><div data-reveal className="mb-12 flex flex-col justify-between gap-7 md:flex-row md:items-end"><div><p className="mono mb-5 text-xs uppercase tracking-[.18em] text-[#16836e]">01 / Selected work</p><h2 className="display max-w-3xl text-5xl font-semibold leading-[.98] tracking-[-.06em] md:text-7xl">Proof is in the<br/><span className="text-[#16836e]">projects.</span></h2></div><p className="max-w-sm text-base leading-7 text-[#5b6470]">Six explorations across product interfaces, institutional websites and data-driven applications. Each one a chance to make something useful.</p></div>
     <div className="grid gap-4 md:grid-cols-2">{projects.map(p=><article data-reveal key={p.n} className={`project-card group relative flex min-h-[330px] flex-col justify-between overflow-hidden rounded-[1.35rem] border border-[#1d2a40]/15 bg-[#e9e6dc] p-7 md:min-h-[370px] md:p-9 ${p.tone==='lime'?'hover:bg-[#e4edba]':p.tone==='coral'?'hover:bg-[#f1d4c7]':p.tone==='blue'?'hover:bg-[#d8e1e2]':''}`}><div className="flex items-start justify-between"><span className="mono text-xs text-[#16836e]">PROJECT / {p.n}</span><a href={p.url} target="_blank" rel="noopener noreferrer" aria-label={`${p.action}: ${p.name} (opens in a new tab)`} className="project-arrow grid h-11 w-11 place-items-center rounded-full border border-[#1d2a40]/20 transition group-hover:rotate-45 group-hover:bg-[#1d2a40] group-hover:text-[#f3f0e8]"><ArrowUpRight size={20}/></a></div><div><p className="mono mb-3 text-[10px] uppercase tracking-[.16em] text-[#77808a]">{p.type}</p><h3 className="display max-w-lg text-3xl font-semibold leading-tight tracking-[-.05em] md:text-[2.6rem]">{p.name}</h3><p className="mt-3 max-w-lg text-sm leading-6 text-[#5b6470]">{p.desc}</p><div className="mt-6 flex flex-wrap items-center justify-between gap-3 border-t border-[#1d2a40]/15 pt-4"><span className="mono text-[10px] text-[#5b6470]">{p.stack}</span><a href={p.url} target="_blank" rel="noopener noreferrer" className="project-link inline-flex items-center gap-1 text-xs font-bold">{p.action}<ArrowRight size={13}/></a></div></div></article>)}</div>
   </section>
    <section id="about" className="bg-[#dce5df]"><div className="mx-auto grid max-w-[1440px] gap-12 px-6 py-24 md:grid-cols-[.85fr_1.15fr] md:px-12 md:py-32 xl:px-20"><div data-reveal><p className="mono mb-5 text-xs uppercase tracking-[.18em] text-[#16836e]">02 / How I think</p><h2 className="display max-w-lg text-5xl font-semibold leading-[.98] tracking-[-.06em] md:text-7xl">Software is a way to <span className="text-[#16836e]">make sense</span> of things.</h2></div><div data-reveal className="pt-2"><p className="max-w-2xl text-xl leading-8 text-[#465365]">The best work sits at the meeting point of a real need and a well-chosen tool. I like moving between the details of a responsive interface, the logic behind a model, and the story a dataset can tell.</p><p className="mt-6 max-w-2xl leading-7 text-[#5b6470]">I’m pursuing a Bachelor of Science in Software Engineering at Kirinyaga University, with growing focus in AI and machine learning. Practical projects have taught me to keep asking: who is this for, what problem does it solve, and how can I make it clearer?</p><div className="mt-12 grid gap-7 border-t border-[#1d2a40]/20 pt-7 sm:grid-cols-3"><div className="principle"><span className="mono text-[10px] uppercase tracking-widest text-[#16836e]">01</span><p className="mt-3 font-bold">Build end to end</p><p className="mt-2 text-sm leading-6 text-[#5b6470]">From responsive frontends to APIs, data layers and deployment.</p></div><div className="principle"><span className="mono text-[10px] uppercase tracking-widest text-[#16836e]">02</span><p className="mt-3 font-bold">Learn by doing</p><p className="mt-2 text-sm leading-6 text-[#5b6470]">Hands-on work across analytics, classification and clustering.</p></div><div className="principle"><span className="mono text-[10px] uppercase tracking-widest text-[#16836e]">03</span><p className="mt-3 font-bold">Stay collaborative</p><p className="mt-2 text-sm leading-6 text-[#5b6470]">Clear communication, teamwork and thoughtful documentation.</p></div></div></div></div></section>
    <section className="mx-auto max-w-[1440px] px-6 py-24 md:px-12 md:py-32 xl:px-20"><div data-reveal className="mb-12"><p className="mono mb-5 text-xs uppercase tracking-[.18em] text-[#16836e]">03 / Tools I reach for</p><h2 className="display text-5xl font-semibold tracking-[-.06em] md:text-7xl">A broad toolkit.<br/><span className="text-[#16836e]">A clear purpose.</span></h2></div><div className="grid border-t border-[#1d2a40]/20 md:grid-cols-3">{skills.map((s,i)=><div data-reveal key={s.title} className={`skill-group py-7 md:px-7 md:py-8 ${i>0?'md:border-l md:border-[#1d2a40]/20':''}`}><div className="flex items-center gap-3"><s.icon size={19} className="text-[#16836e]"/><h3 className="font-bold">{s.title}</h3></div><div className="mt-6 flex flex-wrap gap-2">{s.items.map(x=><span key={x} className="skill-chip rounded-full border border-[#1d2a40]/15 px-3 py-2 text-xs font-medium text-[#4e5c6c]">{x}</span>)}</div></div>)}</div></section>
    <section id="experience" className="bg-[#1d2a40] text-[#f3f0e8]"><div className="mx-auto max-w-[1440px] px-6 py-24 md:px-12 md:py-32 xl:px-20"><div className="grid gap-12 md:grid-cols-[.72fr_1.28fr]"><div data-reveal><p className="mono mb-5 text-xs uppercase tracking-[.18em] text-[#d9f36f]">04 / Field notes</p><h2 className="display text-5xl font-semibold leading-[.98] tracking-[-.06em] md:text-7xl">Learned<br/>in the <span className="text-[#d9f36f]">field.</span></h2><p className="mt-7 max-w-sm leading-7 text-[#bac2c8]">The classroom gives me foundations. Real teams, real datasets and real users teach me how to put them to work.</p></div><div className="timeline space-y-0 border-t border-white/20"><article data-reveal className="experience-item grid gap-5 border-b border-white/20 py-7 md:grid-cols-[150px_1fr]"><p className="mono text-xs text-[#d9f36f]">MAY — AUG 2026<br/>14 WEEKS</p><div><div className="flex flex-wrap items-center gap-3"><BriefcaseBusiness size={18} className="text-[#e97754]"/><h3 className="display text-2xl font-semibold">Software Engineering Intern</h3></div><p className="mt-2 text-sm text-[#c4cbd0]">Kenya Medical Research Institute (KEMRI) · Centre for Global Health Research</p><p className="mt-1 text-xs text-[#99a5b0]">Kisian, Kisumu County</p><ul className="mt-5 grid gap-2 text-sm leading-6 text-[#bac2c8]"><li>— Developed and improved web-based applications and responsive interfaces.</li><li>— Prepared, cleaned and explored datasets with Python, Pandas and NumPy.</li><li>— Visualized data, applied machine-learning concepts to classification and clustering, and worked with relational databases and SQL.</li></ul></div></article>
     <article data-reveal className="experience-item grid gap-5 border-b border-white/20 py-7 md:grid-cols-[150px_1fr]"><p className="mono text-xs text-[#d9f36f]">2024 — PRESENT</p><div className="flex gap-3"><GraduationCap size={19} className="mt-1 shrink-0 text-[#e97754]"/><div><h3 className="display text-2xl font-semibold">BSc Software Engineering</h3><p className="mt-2 text-sm text-[#c4cbd0]">Kirinyaga University</p><p className="mt-3 text-sm leading-6 text-[#bac2c8]">Developing a strong foundation in software engineering, with growing specialization in artificial intelligence and machine learning.</p></div></div></article>
     <article data-reveal className="experience-item grid gap-5 border-b border-white/20 py-7 md:grid-cols-[150px_1fr]"><p className="mono text-xs text-[#d9f36f]">2024 · 2020–23</p><div className="flex gap-3"><Award size={18} className="mt-1 shrink-0 text-[#e97754]"/><div><h3 className="display text-2xl font-semibold">Foundations & recognition</h3><ul className="mt-3 space-y-2 text-sm leading-6 text-[#bac2c8]"><li>Computer Packages — Distinction, Roba Computer School (2024)</li><li>Participant, Computer Society of Kenya Hackathon — rapid software development and prototyping</li><li>KCSE, Ober Boys High School (2020–2023); primary education at Kandiege Primary School (2019)</li></ul></div></div></article></div></div></div></section>
    <section className="mx-auto max-w-[1440px] px-6 py-24 md:px-12 md:py-32 xl:px-20"><div data-reveal className="hackathon-card relative overflow-hidden rounded-[2rem] bg-[#d9f36f] px-7 py-12 md:px-14 md:py-16"><span className="mono text-xs uppercase tracking-[.18em] text-[#395044]">05 / Beyond the screen</span><div className="mt-7 grid gap-8 md:grid-cols-[1fr_1fr] md:items-end"><h2 className="display max-w-xl text-5xl font-semibold leading-[.95] tracking-[-.065em] md:text-7xl">Hackathon pace.<br/>Long-game mindset.</h2><div><p className="max-w-lg leading-7 text-[#465542]">Taking part in the Computer Society of Kenya Hackathon meant building and prototyping under competitive deadlines. The lesson stayed with me: focus on the problem, choose the simplest useful path, and keep shipping.</p><div className="mt-6 inline-flex items-center gap-3 rounded-full border border-[#1d2a40]/20 px-4 py-2.5 text-sm font-bold"><Award size={16}/> Participant · Computer Society of Kenya Hackathon</div></div></div><span aria-hidden="true" className="hackathon-mark pointer-events-none absolute -right-10 -top-24 hidden font-bold leading-none text-[#1d2a40]/[.045] md:block" style={{fontSize:'26rem'}}>+</span></div></section>
    <section id="contact" className="bg-[#e7e3d9]"><div className="mx-auto max-w-[1440px] px-6 py-24 md:px-12 md:py-32 xl:px-20"><p className="mono mb-5 text-xs uppercase tracking-[.18em] text-[#16836e]">06 / Start a conversation</p><div className="grid gap-10 md:grid-cols-[1fr_.7fr] md:items-end"><h2 data-reveal className="display max-w-3xl text-6xl font-semibold leading-[.9] tracking-[-.075em] md:text-[7rem]">Let’s make<br/>something <span className="text-[#16836e]">matter.</span></h2><div data-reveal><p className="mb-6 max-w-md leading-7 text-[#5b6470]">Have a thoughtful project, a question, or an opportunity to learn together? I’d be glad to hear from you.</p><a href="mailto:omondijosephat2005@gmail.com" className="contact-link group flex items-center justify-between border-y border-[#1d2a40]/20 py-5 text-lg font-bold"><span className="flex items-center gap-3"><Mail size={19} className="text-[#16836e]"/>omondijosephat2005@gmail.com</span><ArrowUpRight size={19} className="transition group-hover:-translate-y-1 group-hover:translate-x-1"/></a><a href="tel:+254797670230" className="contact-link group flex items-center justify-between border-b border-[#1d2a40]/20 py-5 text-lg font-bold"><span className="flex items-center gap-3"><Phone size={19} className="text-[#16836e]"/>0797 670 230</span><ArrowUpRight size={19} className="transition group-hover:-translate-y-1 group-hover:translate-x-1"/></a><a href="https://github.com/Josephat200" target="_blank" rel="noopener noreferrer" aria-label="Josphat Omondi on GitHub (opens in a new tab)" className="contact-link group flex items-center justify-between border-b border-[#1d2a40]/20 py-5 text-lg font-bold"><span className="flex items-center gap-3"><Github size={19} className="text-[#16836e]"/>GitHub / Josephat200</span><ExternalLink size={17} className="transition group-hover:-translate-y-1 group-hover:translate-x-1"/></a></div></div></div></section>
  </main>
  <footer className="mx-auto flex max-w-[1440px] flex-col gap-4 px-6 py-7 text-xs text-[#69727d] md:flex-row md:items-center md:justify-between md:px-12 xl:px-20"><a href="#home" className="footer-link font-bold tracking-tight text-[#1d2a40]">Josphat Omondi <span className="text-[#16836e]">© 2026</span></a><span>Software engineering · AI/ML · Data analysis</span><a href="#home" className="back-to-top inline-flex items-center gap-2 font-semibold hover:text-[#16836e]">Back to top <ArrowUpRight size={14}/></a></footer>
 </div>
}
export default App;
